default: &default
  encoding: utf8
  pool: 5
  adapter: postgresql
  username: username
  password: password

development:
  <<: *default
  database: tmp_dev

test:
  <<: *default
  database: tmp_test

production:
  <<: *default
  database: tmp_prod
