default: &default
  encoding: utf8
  pool: 5
  adapter: postgresql
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: starling_bot_dev

test:
  <<: *default
  database: starling_bot_test

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
